Repository Phishing-Database/phishing, pull requests merged in 2021-07, with the labels that each got.

#17 Make readme a bit more explainable
  README.md
Labels: documentation

#26 add cliphot-portugal-vip.xyz
  add-domain
Labels: Need more info, ReBase

#20 add www-rsblox.com
  add-domain
Labels: ReBase

#23 steamcommunytu.ru
  add-domain
Labels: ReBase
