Repository Phishing-Database/phishing, pull requests merged in 2024-12, with the labels that each got.

#530 Update add domain
  add-domain
Labels: Need more info

#535 Update falsepositive.list to add click.ltms.app
  falsepositive.list
Labels: question, Need more info

#541 [FALSE-POSITIVE] walletconnect.network
  falsepositive.list
  falsepositive_all.list
Labels: question

#537 Moneybadger$ host IPs and additional domains
  IP-addr.cidr.in-addr.arpa
  IP-addr.cidr.list
  IP-addr.in-addr.arpa
  IP-addr.list
  add-wildcard-domain
Labels: ReBase

#557 add www.sibalogtv.com to falsepositive.list
  falsepositive.list
Labels: False Positive
