Repository Phishing-Database/phishing, pull requests merged in 2024-02, with the labels that each got.

#318 Update falsepositive.list with Quicksign
  falsepositive.list
Labels: ReBase

#329 Update falsepositive.list
  falsepositive.list
Labels: todo :spiral_notepad:

#332 Update falsepositive.list
  falsepositive.list
Labels: wontfix
